# Generated by Django 2.2 on 2021-02-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='description',
        ),
    ]
