# Generated by Django 2.2 on 2021-02-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_homepagecontent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='image',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='None/no-img.jpg', max_length=150, upload_to='home/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.HomepageContent')),
            ],
        ),
    ]
