# Generated by Django 2.2 on 2021-02-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210211_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
