# Generated by Django 2.2 on 2021-02-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_servicepagecontent_servicepageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicepageTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicepageimage',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicepagecontent',
            name='tab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServicepageTab'),
        ),
    ]
