# Generated by Django 2.2 on 2021-02-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210212_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepagecontent',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ServicepageTab'),
        ),
    ]
