# Generated by Django 2.2 on 2021-02-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210212_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepagetab',
            old_name='tab',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='servicepagecontent',
            name='tab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.ServicepageTab'),
        ),
    ]
