# Generated by Django 2.2 on 2021-02-15 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210212_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagecontent',
            name='tab',
        ),
        migrations.AddField(
            model_name='servicepagetab',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServicepageContent'),
        ),
    ]
