# Generated by Django 2.2 on 2021-02-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210215_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagetab',
            name='page',
        ),
        migrations.AddField(
            model_name='servicepagecontent',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ServicepageTab'),
        ),
    ]
