# Generated by Django 2.2 on 2021-02-15 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210215_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepageimage',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', max_length=150, upload_to='service/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
