# Generated by Django 2.2 on 2021-02-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210215_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepageimage',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', max_length=150, upload_to='service/'),
        ),
    ]
