# Generated by Django 2.2 on 2021-02-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210215_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagecontent',
            name='img',
        ),
        migrations.AlterField(
            model_name='servicepagecontent',
            name='tab',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ServicepageTab',
        ),
    ]
