# Generated by Django 2.2 on 2021-02-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210215_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepageimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.ServicepageContent'),
        ),
    ]
