# Generated by Django 2.2 on 2021-02-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210215_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutpageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quotes', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AboutpageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='None/no-img.jpg', max_length=150, upload_to='about/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.AboutpageContent')),
            ],
        ),
    ]
