# Generated by Django 2.2 on 2021-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_aboutpagecontent_aboutpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quotes',
            field=models.TextField(),
        ),
    ]
