# Generated by Django 2.2 on 2021-02-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210215_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdusenpageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdusenpageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='None/no-img.jpg', max_length=150, upload_to='join/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProdusenpageContent')),
            ],
        ),
    ]
