# Generated by Django 2.2 on 2021-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_produsenpagecontent_produsenpageimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdusenpageContent',
            new_name='JoinpageContent',
        ),
        migrations.RenameModel(
            old_name='ProdusenpageImage',
            new_name='JoinpageImage',
        ),
    ]
