# Generated by Django 2.2 on 2021-02-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210215_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='roles',
            field=models.CharField(default='Contributors', max_length=150),
        ),
    ]
